:address:              smtp.gmail.com
:domain:               gmail.com
:port:                 587
:user_name:            
:password:             
:authentication:       plain
:enable_starttls_auto: true
